routes/web.php
<?php

use App\Exports\Export;
use Maatwebsite\Excel\Facades\Excel;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/loginPortal', 'Auth\LoginController@loginPortal')->name('loginPortal');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/inicio', 'HomeController@inicio')->name('inicio');;
Route::get('/portal', 'HomeController@portal');

// Usuario
Route::resource('/user', 'UserController');
Route::get('/resetUsuario/{id}', 'UserController@resetUsuario');
Route::get('/deleteUsuario/{id}', 'UserController@deleteUsuario');

// Paciente
Route::resource('/paciente', 'PacienteController');
Route::get('buscarPaciente', 'PacienteController@buscarPaciente');
Route::get('getBiopsia', 'PacienteController@getBiopsia');

// Solicitud Pabellon
Route::resource('/solicitudPabellon', 'SolicitudPabellonController');
Route::get('/validador', 'SolicitudPabellonController@validador');
Route::get('/solicitudPabellonDetalle/{id}', 'SolicitudPabellonController@detalle');
Route::get('/indexPausas', 'SolicitudPabellonController@indexPausas');
Route::get('/devolverListaEspera', 'SolicitudPabellonController@devolverListaEspera');
Route::get('/solicitudPabellonCorregir', 'SolicitudPabellonController@corregir');
Route::get('/solicitudPabellonSinPaciente', 'SolicitudPabellonController@solicitudPabellonSinPaciente');

// Consentimiento Informado
Route::resource('/consentimiento', 'ConsentimientoController');

// Pausas
Route::resource('/pausaPre', 'PausaPreController');

Route::resource('/pausaPabellon', 'PausaPabellonController');

Route::resource('/pausaAnestesia', 'PausaAnestesiaController');

Route::resource('/pausaSeguridad', 'PausaSeguridadController');

Route::resource('/pausaIntra', 'PausaIntraController');
Route::get('/agregarAccesoVascular', 'PausaIntraController@agregarAccesoVascular');
Route::get('/agregarDrenaje', 'PausaIntraController@agregarDrenaje');

Route::resource('/pausaRecuento', 'PausaRecuentoController');
Route::get('/agregarGasasCompresas', 'PausaRecuentoController@agregarGasasCompresas');
Route::get('/agregarInstrumental', 'PausaRecuentoController@agregarInstrumental');

Route::resource('/pausaRecuperacion', 'PausaRecuperacionController');
Route::get('/revertirAlta', 'PausaRecuperacionController@revertirAlta');

Route::resource('/pausaEpicrisis', 'PausaEpicrisisController');

Route::resource('/pausaTraslado', 'PausaTrasladoController');

// Protocolo
Route::resource('/protocolo', 'ProtocoloController');
Route::get('/eliminarProtocolo', 'ProtocoloController@eliminarProtocolo');

Route::resource('/informe', 'InformeController');
Route::get('/vaciadoIntervenciones', 'InformeController@vaciadoIntervenciones');
Route::get('/vaciadoIntervencionesExcel', 'InformeController@vaciadoIntervencionesExcel');

// Insumos
Route::resource('/solicitudInsumo', 'SolicitudInsumoController');


// Get
Route::get('/getDatosRut', 'GetController@getDatosRut');
Route::get('/getUser', 'GetController@getUser');
Route::get('/getUnidadDemandante/{id}', 'GetController@getUnidadDemandante');
Route::get('/getDiagnostico', 'GetController@getDiagnostico');
Route::get('/getMedico', 'GetController@getMedico');
Route::get('/getPrestacion', 'GetController@getPrestacion');
Route::get('/getEquipo', 'GetController@getEquipo');
Route::get('/getPrestacionTodas', 'GetController@getPrestacionTodas');
Route::get('/getNrPabellon/{id}', 'GetController@getNrPabellon');
Route::get('/getRut', 'GetController@getRut');
Route::get('/agregarFichaGenPaciente', 'GetController@agregarFichaGenPaciente');

app/Protocolo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Auditable;
use Auth;
use DateTime;

class Protocolo extends Model implements Auditable
{
    protected $table = 'cb_protocolo';

    public $guarded = [];
    protected $appends = ['ges', 'ges_sn', 'lista_espera', 'fecha_intervencion', 'duracion'];

    use \OwenIt\Auditing\Auditable;
    protected $auditEvents = [
        'updated',
        'updating',
        'deleted',
        'deleting',
    ];

    protected $auditThreshold = 200;

    public static function boot()
    {
        parent::boot();

        static::creating(function($protocolo)
        {
            $protocolo->id_medico = Auth::id();
        });
          
        static::created(function($protocolo)
        {
            $protocolo->id_medico = Auth::id();
        });
    }

    public function solicitudPabellon()
    {
		    return $this->hasOne('App\SolicitudPabellon', 'id', 'id_solicitud_pabellon');
    }

    public function medico()
    {
		    return $this->belongsTo('App\User', 'id_medico');
    }

    public function prestacionesOriginales()
    {
        return $this->belongsToMany('App\Prestacion', 'cb_protocolo_presta', 'id_protocolo', 'id_presta', 'id', 'prs_corr');
    }

    public function prestaciones()
    {
        return $this->belongsToMany('App\Prestacion', 'cb_protocolo_presta_estadistica', 'id_protocolo', 'id_presta', 'id', 'prs_corr');
    }

    public function equipo()
    {
		    return $this->hasMany('App\ProtocoloEquipo', 'id_protocolo');
    }

    public function addendum()
    {
		    return $this->hasMany('App\ProtocoloAddendum', 'id_protocolo');
    }

    public function cie10pre()
    {
		    return $this->belongsTo('App\Cie10', 'id_diagnostico_pre');
    }

    public function cie10post()
    {
		    return $this->belongsTo('App\Cie10', 'id_diagnostico_pos');
    }

    public function pabellon()
    {
		return $this->belongsTo('App\Pabellon', 'id_pabellon')->withDefault(["gl_nombre" => "Sin Información"]);
    }

    public function setFcEntradaPabellonAttribute($value) 
    {
        $this->attributes['fc_entrada_pabellon'] = date("Y-m-d H:i:s", strtotime(str_replace("/",".", $value)));
    }
    
    public function setFcSalidaPabellonAttribute($value) 
    {
        $this->attributes['fc_salida_pabellon'] = date("Y-m-d H:i:s", strtotime(str_replace("/",".", $value)));
    }
    
    public function setFcInicioAnesteciaAttribute($value) 
    {
        $this->attributes['fc_inicio_anestecia'] = date("Y-m-d H:i:s", strtotime(str_replace("/",".", $value)));
    }
    
    public function setFcFinAnesteciaAttribute($value) 
    {
        $this->attributes['fc_fin_anestecia'] = date("Y-m-d H:i:s", strtotime(str_replace("/",".", $value)));
    }
    
    public function setFcInicioIntervencionAttribute($value) 
	  {
		    $this->attributes['fc_inicio_intervencion'] = date("Y-m-d H:i:s", strtotime(str_replace("/",".", $value)));
    }
    
    public function setFcFinIntervencionAttribute($value) 
    {
        $this->attributes['fc_fin_intervencion'] = date("Y-m-d H:i:s", strtotime(str_replace("/",".", $value)));
    }

    public function getGesAttribute()
    {
        if($this->bo_auge == 1): return "GES";else: return "No GES"; endif;
    }

    public function getGesSnAttribute()
    {
        if($this->bo_auge == 1): return "S";else: return "N"; endif;
    }

    public function getListaEsperaAttribute()
    {
        if($this->bo_lista_espera == 1): return "SI";else: return "NO"; endif;
    }
  
    public function getFechaIntervencionAttribute()
    {
        $fecha_intervencion = date('d/m/Y', strtotime(str_replace("/",".",$this->fc_entrada_pabellon)));
        return "{$fecha_intervencion}";
    }

    public function getDuracionAttribute()
    {
        $inicioInt = new DateTime($this->fc_inicio_intervencion);
        $terminoInt = new DateTime($this->fc_fin_intervencion);
        $interval = $inicioInt->diff($terminoInt);
        return $interval->format("%H:%i");
    }
}

app/Http/Controllers/ProtocoloController.php
<?php

namespace App\Http\Controllers;

use App\Protocolo;
use App\ProtocoloEquipo;
use App\SolicitudPabellon;
use App\SolicitudPabellonEquipo;
use App\EquipoMedico;
use App\Pabellon;
use App\User;
use Illuminate\Support\Facades\Mail;
use App\Mail\InformationReceived;
use Auth;
use Illuminate\Http\Request;

class ProtocoloController extends Controller
{
    function __construct(){
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $protocolos = Protocolo::with('solicitudPabellon')
                ->whereHas('solicitudPabellon')
                ->orderBy('id', 'DESC')
                ->paginate(10);
        return view('protocolo.index', compact('protocolos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $solicitudPabellon = SolicitudPabellon::with('paciente', 'medico', 'prestaciones', 'equipo', 'equipo.labor', 'equipo.medico', 'asignacion', 'asignacion.nrPabellon', 'protocolo', 'protocolo.prestaciones', 'protocolo.equipo', 'pausaIntra')
                ->find($request->id_solicitud);
        $equiposMedicos = EquipoMedico::orderBy('gl_descripcion')->get();
        $pabellones = Pabellon::where('bo_activo', '1')->get();
        return view('protocolo.register', compact('solicitudPabellon', 'equiposMedicos', 'pabellones'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $solicitudPabellon = SolicitudPabellon::with('paciente')->find(request()->id_solicitud_pabellon);
        $gl_motivo = "";
        if(request()->bo_re_intervencion == 1){
            $gl_motivo = "Aplica Reintervencion";
        }
        if(is_null(request()->gl_diagnostico_pre)){
            request()->gl_diagnostico_pre = '';
        }

        $protocolo = Protocolo::updateOrCreate([
            'id' => request()->id
        ],[
            'id_solicitud_pabellon'=> request()->id_solicitud_pabellon,
            'bo_re_intervencion'=> request()->bo_re_intervencion,
            'bo_lista_espera'=> request()->bo_lista_espera,
            'bo_auge'=> request()->bo_auge,
            'fc_entrada_pabellon'=> date("Y-m-d H:i:s", strtotime(request()->fc_entrada_pabellon)),
            'fc_salida_pabellon'=> date("Y-m-d H:i:s", strtotime(request()->fc_salida_pabellon)),
            'fc_inicio_anestesia'=> date("Y-m-d H:i:s", strtotime(request()->fc_inicio_anestesia)),
            'fc_fin_anestesia'=> date("Y-m-d H:i:s", strtotime(request()->fc_fin_anestesia)),
            'fc_inicio_intervencion'=> date("Y-m-d H:i:s", strtotime(request()->fc_inicio_intervencion)),
            'fc_fin_intervencion'=> date("Y-m-d H:i:s", strtotime(request()->fc_fin_intervencion)),
            'id_diagnostico_pre'=> request()->id_diagnostico_pre,
            'gl_diagnostico_pre'=> request()->gl_diagnostico_pre,
            'id_diagnostico_pos'=> request()->id_diagnostico_pos,
            'gl_diagnostico_pos'=> request()->gl_diagnostico_pos,
            'gl_cirugia_practicada'=> request()->gl_cirugia_practicada,
            'gl_riesgo_operatorio'=> request()->gl_riesgo_operatorio,
            'gl_tipo_anestesia'=> request()->gl_tipo_anestesia,
            'gl_hallazgo'=> request()->gl_hallazgo,
            'gl_descripcion'=> request()->gl_descripcion,
            'gl_incidencia_qui'=> request()->gl_incidencia_qui,
            'gl_incidencia_ane'=> request()->gl_incidencia_ane,
            'bo_drenaje'=> request()->bo_drenaje,
            'bo_biopsia'=> request()->bo_biopsia,
            'bo_cultivo'=> request()->bo_cultivo,
            'gl_tipo_herida'=> request()->gl_tipo_herida,
            'nr_perdida_sanguinea'=> request()->nr_perdida_sanguinea,
            'gl_tromboembolica'=> request()->gl_tromboembolica,
            'bo_tratamiento_antibiotico'=> request()->bo_tratamiento_antibiotico,
            'bo_profilosis'=> request()->bo_profilosis,
            'bo_gasa'=> request()->bo_gasa,
            'bo_material'=> request()->bo_material,
            'bo_compresa'=> request()->bo_compresa,
            'bo_eliminado'=> 0,
            'id_diagnostico_estadistica'=> request()->id_diagnostico_pos,
            'id_tipo_intervencion'=> 0,
            'id_clase_intervencion'=> 0,
            'id_equipo'=> request()->id_equipo,
            'bo_antiguo'=> 0,
            'gl_motivo'=> $gl_motivo,
            'bo_procuramiento'=> request()->bo_procuramiento,
            'bo_cancer'=> request()->bo_cancer
        ]);

        // Prestaciones
        $solicitudPabellon->prestaciones()->sync($request->intervencion);
        $protocolo->prestacionesOriginales()->sync($request->intervencion);
        $protocolo->prestaciones()->sync($request->intervencion);

        //Equipo
        $equipoDelete = SolicitudPabellonEquipo::where('id_solicitud', $solicitudPabellon->id)->delete();
        foreach ($request->equipos as $key => $equipo) {
            $equipo = explode("-", $equipo);
            SolicitudPabellonEquipo::updateOrCreate([
                'id_solicitud' => $solicitudPabellon->id,
                'id_medico' => $equipo[0]
            ],[
                'id_solicitud' => $solicitudPabellon->id,
                'id_medico' => $equipo[0],
                'cd_labor' => $equipo[1]
            ]);
        }
        $equipoDelete = ProtocoloEquipo::where('id_protocolo', $protocolo->id)->delete();
        foreach ($request->equipos as $key => $equipo) {
            $equipo = explode("-", $equipo);
            ProtocoloEquipo::updateOrCreate([
                'id_protocolo' => $protocolo->id,
                'id_medico' => $equipo[0]
            ],[
                'id_protocolo' => $protocolo->id,
                'id_medico' => $equipo[0],
                'cd_labor' => $equipo[1]
            ]);
        }

        if($protocolo){
            $solicitudPabellon->id_estado = 3;
            $solicitudPabellon->save();
            return redirect('/paciente/'.$solicitudPabellon->id_paciente)->with('message', "Se ha creado el Protocolo");
        }else{
            return redirect('/paciente/'.$solicitudPabellon->id_paciente)->with('error', "No se ha creado el Protocolo");
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Protocolo  $protocolo
     * @return \Illuminate\Http\Response
     */
    public function show(Protocolo $protocolo)
    {
        $solicitudPabellon = SolicitudPabellon::with('paciente', 'medico', 'prestaciones', 'equipo', 'equipo.labor', 'equipo.medico', 'asignacion', 'asignacion.nrPabellon', 'protocolo', 'protocolo.prestaciones', 'protocolo.equipo', 'pausaIntra')
                ->whereHas('protocolo', function ($query) use ($protocolo){
                    $query->where('id', $protocolo->id);
                })
                ->first();

        $pdf = \PDF::loadView('protocolo.show', compact('solicitudPabellon'));
     
        return $pdf->stream('archivo.pdf');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Protocolo  $protocolo
     * @return \Illuminate\Http\Response
     */
    public function edit(Protocolo $protocolo)
    {
        $solicitudPabellon = SolicitudPabellon::with('paciente', 'medico', 'prestaciones', 'equipo', 'equipo.labor', 'equipo.medico', 'asignacion', 'asignacion.nrPabellon', 'protocolo', 'protocolo.prestaciones', 'protocolo.equipo', 'pausaIntra')
                ->whereHas('protocolo', function ($query) use ($protocolo){
                    $query->where('id', $protocolo->id);
                })
                ->first();
        foreach ($solicitudPabellon->protocolo->equipo as $key => $equipo) {
            $equipo->id_new = $equipo->medico->pro_cod.'-'.$equipo->labor->cod_car;
        }
        $equiposMedicos = EquipoMedico::orderBy('gl_descripcion')->get();
        $pabellones = Pabellon::where('bo_activo', '1')->get();
        return view('protocolo.register', compact('solicitudPabellon', 'equiposMedicos', 'pabellones'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Protocolo  $protocolo
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Protocolo $protocolo)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Protocolo  $protocolo
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $user = User::find($request->id_user);
        $request->request->add(['usuario_solicitante' => $user->gl_nombre]);
        $protocolo = Protocolo::with('prestacionesOriginales', 'prestaciones', 'equipo', 'addendum')->find($request->id);
        $solicitudPabellon = SolicitudPabellon::with('paciente')->find($protocolo->id_solicitud_pabellon);
        $solicitudPabellon->id_estado = 2;
        $solicitudPabellon->save();
        $request->request->add(['protocolo' => $protocolo]);
        $request->request->add(['id_correo' => 1]);
        Mail::to($request->receptor)->send(new InformationReceived($request));
        $protocolo->prestacionesOriginales()->detach();
        $protocolo->prestaciones()->detach();
        $protocolo->equipo()->delete();
        $protocolo->addendum()->delete();
        $protocolo->delete();
        return redirect('/paciente/'.$solicitudPabellon->id_paciente)->with('message', "Se ha eliminado el protocolo");
    }

    public function eliminarProtocolo(Request $request)
    {

resources/views/protocolo/correoEliminar.blade.php
<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0">
    <title>Eliminación de Protocolo</title>
</head>
<body>
    <h2>Eliminacion de Protocolo de solicitud N° {{$request->protocolo->id_solicitud_pabellon}}</h2>
    <p>Motivo: {{($request->mensaje)}}</p>
    <p>Solicitado Por: {{$request->usuario_solicitante}}.</p>
    <br>
    <br>
    {{$request->protocolo}}
    {{-- <p>Favor no responder este correo, si tienes dudas comunicarte directamente al correo del emisor del mensaje.</p> --}}
</body>
</html>

resources/views/protocolo/datos.blade.php
<div class="card-body">
    <div class="row invoice-info">
        <div class="col-sm-6 invoice-col">
            <strong>Cirujano: </strong>{{$solicitudPabellon->protocolo->medico->nombre}}<br>
            <strong>Pabellón: </strong>{{$solicitudPabellon->asignacion->pabellon->nombre}}<br>
        </div>
        <div class="col-sm-6 invoice-col">
            <strong>Fecha (Entrada Pabellón): </strong>{{date('d/m/Y H:i:s', strtotime(str_replace("/",".",$solicitudPabellon->protocolo->fc_entrada_pabellon)))}}<br>
            <strong>Sala: </strong>{{$solicitudPabellon->asignacion->nrPabellon->gl_nombre}}<br>
        </div>
    </div>
    <strong>Diagnostico Pre-Operatorio Cie10: </strong>{{$solicitudPabellon->protocolo->cie10pre->gl_glosa}}<br>
    <strong>Diagnostico Pre-Operatorio: </strong>{{$solicitudPabellon->protocolo->gl_diagnostico_pre}}<br>
    <strong>Diagnostico Post-Operatorio Cie10: </strong>{{$solicitudPabellon->protocolo->cie10post->gl_glosa}}<br>
    <strong>Diagnostico Post-Operatorio: </strong>{{$solicitudPabellon->protocolo->gl_diagnostico_post}}<br>
</div>

resources/views/protocolo/eliminar.blade.php
@extends('adminlte::page')

@section('title', 'Eliminar Protocolo')

@section('content_header')
    <h1><i class="ace-icon fa fa-user-md"></i> Eliminar Protocolo N° {{$solicitudPabellon->protocolo->id}}</h1>
@stop

@section('content')
    <div class="card">
        <!-- form start -->
        <form action="{{ route('protocolo.destroy',$solicitudPabellon->protocolo->id) }}" method="POST">
        {{-- <form role="form" class="form-horizontal" id="form" method="POST" action="{{action('ProtocoloController@store')}}"> --}}
        {{ csrf_field() }}
        <input type="hidden" id="id" name="id" value="{{isset($solicitudPabellon) ? $solicitudPabellon->protocolo->id : ''}}"/>
        <input type="hidden" id="id_solicitud_pabellon" name="id_solicitud_pabellon" value="{{isset($solicitudPabellon) ? $solicitudPabellon->id : ''}}"/>
        <div class="card-header">
            <h3 style="color:green" class="card-title"><strong>Datos Paciente</strong></h3>
        </div>
        <div class="card-body">
            <div class="row invoice-info">
                <div class="col-sm-6 invoice-col">
                    @if($solicitudPabellon->paciente->id_tipo_identificacion_paciente == 1)
                        <strong>Rut: </strong>{{$solicitudPabellon->paciente->rut}}<br>
                    @else
                        <strong>Pasaporte: </strong>{{$solicitudPabellon->paciente->tx_pasaporte}}<br>
                    @endif
                    <strong>Ficha: </strong>
                    @if(isset($solicitudPabellon->paciente->nr_ficha))
                        {{$solicitudPabellon->paciente->nr_ficha}}
                    @else
                        Sin Información
                    @endif<br>
                    <strong>Fecha de Nacimiento: </strong>
                    @if($solicitudPabellon->paciente->fc_nacimiento != '0000-00-00')
                        {{date('d/m/Y', strtotime(str_replace("/",".",$solicitudPabellon->paciente->fc_nacimiento)))}} ({{$solicitudPabellon->paciente->edad}})
                    @else 
                        Sin Información
                    @endif<br>
                    <strong>Previsión: </strong>{{$solicitudPabellon->paciente->prevision->tx_descripcion}} {{$solicitudPabellon->paciente->clasificacionFonasa->tx_descripcion}}
                </div>
                <!-- /.col -->
                <div class="col-sm-6 invoice-col">
                    <strong>Nombre: </strong>{{$solicitudPabellon->paciente->nombre}}<br>
                    <strong>Sexo: </strong>{{$solicitudPabellon->paciente->sexo->tx_descripcion}}<br>
                    <strong>Dirección: </strong>{{$solicitudPabellon->paciente->tx_direccion}}<br>
                    <strong>Telefono: </strong>
                    @if(isset($solicitudPabellon->paciente->tx_telefono))
                        {{$solicitudPabellon->paciente->tx_telefono}}
                    @else
                        Sin Información
                    @endif
                </div>
                <!-- /.col -->
            </div>
        </div>

        <div class="card-body">
            <div class="row form-group">
                <div class="col-sm-4">
                    <label for="receptor">Mail:</label>
                    <select class="select2 select2-hidden-accessible" id="receptor" name="receptor[]" multiple="" data-placeholder="Seleccione mail(s)" style="width: 100%;" data-select2-id="7" tabindex="-1" aria-hidden="true" required>
                        @foreach ($usuarios as $usuario)
                            <option value="{{$usuario->gl_mail}}">{{$usuario->gl_nombre}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-sm-4">
                    <label for="id_user">Usuario Solicitante</label>
                    <select class="form-control select_users" id="id_user" name="id_user" required>
                    </select>
                </div>
                <div class="col-sm-4">
                    <label for="mensaje">Motivo</label>
                    <textarea type="text" class="form-control" id="mensaje" name="mensaje" required></textarea>
                </div>
            </div>
        </div>

        <div class="card-footer text-right">
            @method('DELETE')
            <button onclick="guardar()" type="submit" class="btn btn-danger">Eliminar Protocolo</button>
        </div>
        </form>
    </div>
@stop

@section('js')
<script>
    $("body").addClass("sidebar-collapse");
    var url_users = @json(url('getUser'));

    $(".select2-general").select2({
        placeholder: "Seleccionar",
        allowClear: true
    })

    $('#receptor').select2();

    $('.select_users').select2({
        width: '99%',
        allowClear: true,
        minimumInputLength: 3,
        placeholder: "Seleccione Usuario",
        language: {
            inputTooShort: function() {
                return 'Ingrese 3 o más caracteres para la búsqueda';
            }
        },
        ajax: {
            url: url_users,
            dataType: 'json',
            data: function (params) {
                var query = {
                    search: params.term,
                    type: 'public'
                }
                return query;
            }
        }
    });
</script>
@stop